version: '3'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${LGS_HOST_SUBNET}/24
services:
  mongo:
    restart: always
    image: mongo
    ports:
      - 27018:27018
    volumes:
      - /data/storage/team-builder.mongodb:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --port 27018
    env_file:
      - .env
  app:
    command: npm run start
    image: ${LGS_DOCKER_IMAGE}
    restart: always
    working_dir: /usr/src/app/server
    ports:
      - 5001:5001
    volumes:
      - /data/logs/team-builder:/usr/src/app/server/logs
      - /data/logs/team-builder/npm:/root/.npm/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
    env_file:
      - .env
